package Analizadores;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PRPROGRAM = 11;
  public static final int DISTINTO = 34;
  public static final int PRAND = 39;
  public static final int RESTA = 36;
  public static final int PC = 23;
  public static final int PA = 22;
  public static final int PRWHILE = 29;
  public static final int PRSTRING = 17;
  public static final int PRFLOAT = 16;
  public static final int CONST_HEXA = 8;
  public static final int SUMA = 35;
  public static final int CONST_FLOAT = 6;
  public static final int CC = 21;
  public static final int MAYIGUAL = 31;
  public static final int CA = 20;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int CONST_BIN = 7;
  public static final int error = 1;
  public static final int COMA = 3;
  public static final int PRELSE = 28;
  public static final int MENOR = 13;
  public static final int PREND = 12;
  public static final int PRCONTAR = 41;
  public static final int MAYOR = 14;
  public static final int PROR = 40;
  public static final int PRDEFINE = 9;
  public static final int MENIGUAL = 32;
  public static final int PRWRITE = 30;
  public static final int PRIF = 27;
  public static final int CONST_STRING = 5;
  public static final int ASIGN = 26;
  public static final int DIVISION = 38;
  public static final int LLAVEC = 25;
  public static final int PRENDDEFINE = 10;
  public static final int LLAVEA = 24;
  public static final int DP = 18;
  public static final int EQUIVALENTE = 33;
  public static final int PRINT = 15;
  public static final int MULTIPLICACION = 37;
  public static final int CONST_INT = 4;
  public static final int PYC = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "COMA",
  "CONST_INT",
  "CONST_STRING",
  "CONST_FLOAT",
  "CONST_BIN",
  "CONST_HEXA",
  "PRDEFINE",
  "PRENDDEFINE",
  "PRPROGRAM",
  "PREND",
  "MENOR",
  "MAYOR",
  "PRINT",
  "PRFLOAT",
  "PRSTRING",
  "DP",
  "PYC",
  "CA",
  "CC",
  "PA",
  "PC",
  "LLAVEA",
  "LLAVEC",
  "ASIGN",
  "PRIF",
  "PRELSE",
  "PRWHILE",
  "PRWRITE",
  "MAYIGUAL",
  "MENIGUAL",
  "EQUIVALENTE",
  "DISTINTO",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "PRAND",
  "PROR",
  "PRCONTAR"
  };
}

